# Generated by Django 3.2.7 on 2021-10-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='last_name')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='phone_number')),
                ('roll_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='roll_number')),
                ('uid', models.CharField(max_length=20, null=True, verbose_name='uid')),
                ('section', models.CharField(max_length=20, null=True, verbose_name='section')),
                ('dob', models.DateField(max_length=20, null=True, verbose_name='dob')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200, null=True)),
                ('sub_type', models.CharField(max_length=200, null=True)),
                ('short_form', models.CharField(max_length=200, null=True)),
                ('conducted', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.IntegerField(null=True)),
                ('total_hours_absent', models.IntegerField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
