# Generated by Django 3.2.7 on 2021-10-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_student_absence_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_absence_details',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10),
        ),
    ]
