# Generated by Django 3.2.7 on 2021-10-22 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_student_absence_details_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_absence_details',
            name='number_of_periods_absent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student_absence_details',
            name='stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_absence_details',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.subject'),
        ),
        migrations.AddField(
            model_name='student_absence_details',
            name='which_period',
            field=models.CharField(choices=[('Period 1', 'Period 1'), ('Period 2', 'Period 2'), ('Period 3', 'Period 3'), ('Period 4', 'Period 4'), ('Period 5', 'Period 5'), ('Period 6', 'Period 6'), ('Period 7', 'Period 7'), ('Period 8', 'Period 8')], max_length=20, null=True),
        ),
    ]
