# Generated by Django 3.2.7 on 2021-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20211022_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
