# Generated by Django 3.2.7 on 2021-10-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_subject_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_absence_details',
            name='which_period',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=20, null=True),
        ),
    ]
