# Generated by Django 3.2.7 on 2021-10-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_student_absence_details_which_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_absence_details',
            name='number_of_periods_absent',
        ),
    ]
