# Generated by Django 4.0.3 on 2022-04-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20220204_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=860, null=True),
        ),
    ]
