# Generated by Django 3.2.7 on 2021-10-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_remove_student_absence_details_number_of_periods_absent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_absence_details',
            old_name='days',
            new_name='day',
        ),
    ]
