# Generated by Django 3.2.7 on 2021-10-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_rename_days_student_absence_details_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_of_periods_absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_periods_absent', models.IntegerField(null=True)),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.subject')),
            ],
        ),
    ]
