# Generated by Django 3.2.7 on 2021-10-23 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_number_of_periods_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_of_periods_absent',
            name='stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
