# Generated by Django 3.2.7 on 2021-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_number_of_periods_absent_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_id',
            field=models.IntegerField(null=True),
        ),
    ]
