# Generated by Django 3.2.7 on 2021-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_subject_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='registration_number'),
        ),
    ]
