# Generated by Django 3.2.7 on 2021-10-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitted_through',
            field=models.CharField(max_length=20, null=True, verbose_name='admitted_through'),
        ),
        migrations.AddField(
            model_name='student',
            name='applied_year',
            field=models.CharField(max_length=20, null=True, verbose_name='applied_year'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=20, null=True, verbose_name='course'),
        ),
    ]
