# Generated by Django 3.2.7 on 2021-10-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20211026_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True, verbose_name='course'),
        ),
    ]
