# Generated by Django 3.2.7 on 2021-10-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admitted_through',
            field=models.CharField(max_length=200, null=True, verbose_name='admitted_through'),
        ),
    ]
