# Generated by Django 3.2.7 on 2021-10-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_student_admitted_through'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='application_number',
        ),
    ]
