# Generated by Django 3.2.7 on 2021-10-26 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_rename_registration_number_student_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200, null=True)),
                ('total_amount', models.CharField(max_length=200, null=True)),
                ('paid_amount', models.CharField(max_length=200, null=True)),
                ('balance', models.CharField(max_length=200, null=True)),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
