# Generated by Django 3.2.7 on 2021-10-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_fee_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Payment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_number', models.IntegerField(null=True)),
                ('recipt_date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
