# Generated by Django 3.2.7 on 2021-10-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_fee_payment_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee_payment_history',
            old_name='recipt_date',
            new_name='receipt_date',
        ),
        migrations.RenameField(
            model_name='fee_payment_history',
            old_name='recipt_number',
            new_name='receipt_number',
        ),
    ]
