# Generated by Django 3.2.7 on 2021-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_auto_20211026_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Leave_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022')], max_length=200)),
                ('out_pass_type', models.CharField(choices=[('Medical', 'Medical'), ('Casual', 'Casual'), ('Festive', 'Festive')], max_length=20)),
                ('out_pass_from', models.DateTimeField(null=True)),
                ('out_pass_to', models.DateTimeField(null=True)),
                ('roll_number', models.CharField(max_length=20, null=True, verbose_name='roll_number')),
                ('request_type', models.CharField(choices=[('Parents Request', 'Parents Request'), ('Self Request', 'Self Request'), ('Both', 'Both')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
    ]
