# Generated by Django 3.2.7 on 2021-10-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_hostel_leave_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_leave_entry',
            name='out_pass_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hostel_leave_entry',
            name='out_pass_to',
            field=models.DateField(null=True),
        ),
    ]
