# Generated by Django 3.2.7 on 2021-10-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_auto_20211026_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Student Details Change', 'Student Details Change'), ('Attendance Related Issue', 'Attendance Related Issue'), ('Fee Related Issue', 'Fee Related Issue'), ('Other Issue', 'Other Issue')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
