# Generated by Django 3.2.7 on 2021-10-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_support_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
