# Generated by Django 3.2.7 on 2021-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_support_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_request',
            name='date_of_submission',
            field=models.DateField(max_length=20, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='support_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
