# Generated by Django 3.2.7 on 2021-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auto_20211026_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_request',
            name='date_of_submission',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
