# Generated by Django 3.2.7 on 2021-10-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_support_request_date_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_request',
            name='request_id',
            field=models.IntegerField(default=466, null=True),
        ),
    ]
