# Generated by Django 3.2.7 on 2021-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_support_request_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_request',
            name='stu',
        ),
        migrations.AddField(
            model_name='support_request',
            name='roll_number',
            field=models.CharField(max_length=20, null=True, verbose_name='roll_number'),
        ),
        migrations.AlterField(
            model_name='support_request',
            name='request_id',
            field=models.IntegerField(default=248, null=True),
        ),
        migrations.AlterField(
            model_name='support_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In_Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
