# Generated by Django 3.2.7 on 2021-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20211026_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Request_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, null=True, verbose_name='roll_number')),
                ('category_name', models.CharField(choices=[('Student Details Change', 'Student Details Change'), ('Attendance Related Issue', 'Attendance Related Issue'), ('Fee Related Issue', 'Fee Related Issue'), ('Other Issue', 'Other Issue')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In_Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('date_of_submission', models.DateField(auto_now=True, null=True)),
                ('request_id', models.IntegerField(default=426, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Support_Request',
        ),
    ]
