# Generated by Django 3.2.7 on 2022-02-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20220204_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True, verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=277, null=True),
        ),
    ]
