# Generated by Django 3.2.7 on 2022-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20220204_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admitted_through',
            field=models.CharField(max_length=200, null=True, verbose_name='Admitted Through'),
        ),
        migrations.AlterField(
            model_name='student',
            name='application_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='applied_year',
            field=models.CharField(max_length=20, null=True, verbose_name='Applied Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(max_length=20, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Roll Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=20, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=20, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=773, null=True),
        ),
    ]
