# Generated by Django 3.2.7 on 2022-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20220204_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admitted_through',
        ),
        migrations.RemoveField(
            model_name='student',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='applied_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uid',
        ),
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=484, null=True),
        ),
    ]
