# Generated by Django 3.2.7 on 2022-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20220204_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='student',
            name='admitted_through',
            field=models.CharField(max_length=200, null=True, verbose_name='Admitted Through'),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_address',
            field=models.CharField(max_length=500, null=True, verbose_name='alternate_address'),
        ),
        migrations.AddField(
            model_name='student',
            name='application_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='applied_year',
            field=models.CharField(max_length=20, null=True, verbose_name='Applied Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(max_length=20, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='house_number',
            field=models.CharField(max_length=5, null=True, verbose_name='house_number'),
        ),
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.CharField(max_length=10, null=True, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=20, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=20, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=629, null=True),
        ),
    ]
