# Generated by Django 4.1 on 2022-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_support_request_form_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=791, null=True),
        ),
    ]
