# Generated by Django 4.1.5 on 2023-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_support_request_form_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_request_form',
            name='request_id',
            field=models.IntegerField(default=503, null=True),
        ),
    ]
